# Use an official Python runtime as a parent image
FROM frolvlad/alpine-python3:latest

# Install any needed dependencies specified in requirements.txt
RUN pip3 install requests && \
    rm -r /root/.cache

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

#RUN pip install --no-cache-dir -r requirements.txt

# Define environment variable
ENV LOG=1

# Run authentication test script when the container launches
CMD ["python", "authentication_test.py"]


